apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-sink-connector
  namespace: connectors
data:
  connector.json: '{
   "name": "jms-sink-connector",
   "config": {
    "name": "jms-sink-connector",
    "connector.class": "io.confluent.connect.jms.JmsSinkConnector",
    "tasks.max": 1,
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://schemaregistry.confluent.svc.cluster.local:8081",
    "errors.retry.timeout": 0,
    "errors.retry.delay.max.ms": 60000,
    "errors.tolerance": "all",
    "errors.log.enable": "true",
    "errors.log.include.messages": "true",
    "topics": "transactions",
    "errors.deadletterqueue.topic.name": "test1_DLQ",
    "errors.deadletterqueue.topic.replication.factor": "1",
    "errors.deadletterqueue.context.headers.enable": "true",
    "java.naming.provider.url": "jdbc:oracle:thin:@10.105.165.19:1521/XE",
    "java.naming.factory.initial": "oracle.jms.AQjmsInitialContextFactory",
    "connection.factory.name": "ConnectionFactory",
    "java.naming.security.principal": "sys as sysdba",
    "java.naming.security.credentials": "oracle",
    "jms.destination.name": "SYS.SINK_JMS",
    "jms.destination.type": "queue",
    "confluent.license": "",
    "confluent.topic.bootstrap.servers": "kafka.confluent.svc.cluster.local:9071",
    "confluent.topic": "_confluent-command",
    "confluent.topic.replication.factor": 3,
    "db_url": "jdbc:oracle:thin:@10.105.165.19:1521/XE"
   }
 }'
