apiVersion: v1
kind: Namespace
metadata:
  name: oracle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle-xe-11g-r2
        image: wnameless/oracle-xe-11g-r2
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_ALLOW_REMOTE
          value: "true"
        - name: ORACLE_DISABLE_ASYNCH_IO
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: oracle
spec:
  selector:
    app: oracle
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      name: oracle-port
