apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: oracle
spec:
  selector:
    app: oracle
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      name: oracle-port
