apiVersion: batch/v1
kind: Job
metadata:
  name: sdms-unifiedpost-blob-source-connector
  namespace: sdms-common-dev
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - -s
        - -X
        - POST
        - -H
        - 'Content-Type: application/json'
        - --data
        - '@/etc/config/connector/connector.json'
        - http://sdms-kafka-connectors:8085/connectors
        image: cnfldemos/alpine-curl:3.10.2_7.65.1
        imagePullPolicy: IfNotPresent
        name: sdms-unifiedpost-blob-source-connector
        volumeMounts:
        - mountPath: /etc/config/connector
          name: blob-source-connector
      restartPolicy: Never
      volumes:
      - configMap:
          name: sdms-unifiedpost-blob-source-connector
        name: blob-source-connector
  ttlSecondsAfterFinished: 300
