apiVersion: batch/v1
kind: Job
metadata:
  name: sdms-status-sink-storageblob-unifiedpost
  namespace: sdms-common-dev
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - -s
        - http://sdms-kafka-connectors:8085/connectors/sink-storageblob-unifiedpost/status
        image: cnfldemos/alpine-curl:3.10.2_7.65.1
        imagePullPolicy: IfNotPresent
        name: sdms-status-sink-storageblob-unifiedpost
      restartPolicy: Never
  ttlSecondsAfterFinished: 6
