apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test1
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name:            kafka
  kafkaRest:
    endpoint:        http://kafka.confluent.svc.cluster.local:8090
